version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/java-tutorial
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew clean test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/java-tutorial
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew clean build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/reports/tests/test
           
workflows:
  version: 2
  build-test:
    jobs:
    - test:
        filters:
          branches:
            ignore: 
            - master
    - build:
        filters:
          branches:
            only: master